package com.earthpol.earthpollib.config;

import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.configuration.InvalidConfigurationException;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.plugin.Plugin;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.UnmodifiableView;

import java.io.File;
import java.io.IOException;
import java.util.Collection;
import java.util.Collections;
import java.util.EnumMap;
import java.util.HashSet;
import java.util.List;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.logging.Logger;

/**
 * Binds a YAML configuration file to a specific enum of keys
 * ({@code E extends Enum & ReloadableConfiguration}).
 *
 * <p>Responsibilities:</p>
 * <ul>
 *   <li>Stores the enum class and constants in declaration order.</li>
 *   <li>Maintains an {@link EnumMap} from enum constant to its {@link ReloadableConfigNode}.</li>
 *   <li>Creates the config file if missing, writes/fills defaults from the enum’s nodes, and
 *       reparses values from disk into the nodes.</li>
 * </ul>
 *
 * <p><strong>Sync model:</strong> Node values are refreshed from disk on construction and on
 * {@link #reload()}. If you change values through {@link #set(Enum, Object)}, both the in-memory
 * node value and the in-memory YAML are updated; call {@link #save()} to persist those changes.
 * If you mutate the raw {@link #yaml()} directly, call {@link #save()} followed by {@link #reload()}
 * to reparse values back into nodes.</p>
 *
 * @param <E> the enum type that implements {@link ReloadableConfiguration}
 * @since 1.5.0
 */
@SuppressWarnings("unused")
public final class ReloadableConfigHandler<E extends Enum<E> & ReloadableConfiguration> {

    private final Plugin plugin;
    private final File configFile;
    private final Class<E> enumType;
    private final E[] keys;
    private final EnumMap<E, ReloadableConfigNode<?>> map;
    private YamlConfiguration yaml;

    private static final List<String> configHeader =
            List.of(
                    "Config file generated by EarthPolLib",
                    "This file is initially generated from code defaults.",
                    "If a key is missing or malformed, the plugin will fall back to the default value.",
                    "Strings can be quoted or unquoted. If a string doesn't parse correctly, try quoting it."
            );

    public ReloadableConfigHandler(Plugin plugin,
                                   String configFileName,
                                   Class<E> enumType) throws IOException {

        this.plugin   = Objects.requireNonNull(plugin, "plugin");
        this.enumType = Objects.requireNonNull(enumType, "enumType");

        this.keys = enumType.getEnumConstants();
        if (this.keys == null) throw new IllegalArgumentException("Not an enum: " + enumType);

        this.map = new EnumMap<>(enumType);
        final Set<String> seenPaths = new HashSet<>();
        for (E k : keys) {
            ReloadableConfigNode<?> node = k.node();
            String path = node.getYmlPath();
            if (!seenPaths.add(path)) {
                throw new IllegalStateException("Duplicate config node path detected: " + path
                        + " (in " + enumType.getSimpleName() + ")");
            }
            map.put(k, node);
        }

        boolean isNew = !(new File(plugin.getDataFolder(), configFileName)).exists();
        this.configFile = YMLBuilder.fileInitialSetup(plugin, configFileName);

        Collection<ReloadableConfigNode<?>> nodesView = map.values();
        if (isNew) {
            YMLBuilder.buildNewConfiguration(this.configFile, nodesView, configHeader);
        } else {
            YMLBuilder.fillMissingDefaults(this.configFile, nodesView, configHeader);
        }

        this.yaml = YamlConfiguration.loadConfiguration(this.configFile);
        this.yaml.options().parseComments(true);
        reparseIntoNodes(false);
    }

    public synchronized boolean reload() throws IOException {
        YMLBuilder.fillMissingDefaults(
                this.configFile,
                map.values(),
                configHeader
        );
        this.yaml = YamlConfiguration.loadConfiguration(this.configFile);
        this.yaml.options().parseComments(true);
        return reparseIntoNodes(true);
    }

    /**
     * Stages and validates the whole file before applying any live values. Invalid YAML or values
     * leave active nodes and yaml() unchanged. Missing keys use defaults without rewriting the file.
     * Restart-only changes are reported and retained on disk; other validated values are applied.
     * Use snapshot() for a consistent view across handler reloads; direct node mutations are not coordinated.
     */
    public synchronized ConfigReloadResult reloadValidated() throws IOException {
        YamlConfiguration candidate = new YamlConfiguration();
        candidate.options().parseComments(true);
        try {
            candidate.load(configFile);
        } catch (InvalidConfigurationException ex) {
            return new ConfigReloadResult(false, Map.of("<file>", "Invalid YAML: " + ex.getMessage()), Set.of());
        }

        Map<String, String> errors = new LinkedHashMap<>();
        Set<String> restart = new HashSet<>();
        EnumMap<E, Object> staged = new EnumMap<>(enumType);
        for (E key : keys) {
            ReloadableConfigNode<?> node = map.get(key);
            if (node instanceof SectionHeaderNode) continue;
            try {
                if (!candidate.contains(node.getYmlPath())) candidate.set(node.getYmlPath(), node.getDefaultValue());
                Object value = validatedValue(node, readNode(candidate, node));
                if (node.isRestartRequired() && !Objects.equals(node.getValue(), value)) {
                    restart.add(node.getYmlPath());
                } else {
                    staged.put(key, value);
                }
            } catch (RuntimeException ex) {
                errors.put(node.getYmlPath(), Objects.toString(ex.getMessage(), ex.getClass().getSimpleName()));
            }
        }
        if (!errors.isEmpty()) return new ConfigReloadResult(false, errors, restart);
        staged.forEach((key, value) -> applyValidated(map.get(key), value));
        this.yaml = candidate;
        return new ConfigReloadResult(true, Map.of(), restart);
    }

    /** A read-only copy of active values, captured consistently against handler reload/set calls. */
    public synchronized Map<E, Object> snapshot() {
        EnumMap<E, Object> values = new EnumMap<>(enumType);
        for (E key : keys) values.put(key, map.get(key).getValue());
        return Collections.unmodifiableMap(values);
    }

    @SuppressWarnings("unchecked")
    private boolean reparseIntoNodes(boolean reloading) {
        boolean ok = true;
        Logger log = plugin.getLogger();
        for (ReloadableConfigNode<?> n : map.values()) {
            ok &= loadIntoNode(this.yaml, n, log, reloading);
        }
        return ok;
    }

    @SuppressWarnings("unchecked")
    private static boolean loadIntoNode(FileConfiguration yaml,
                                        ReloadableConfigNode<?> node,
                                        Logger log, boolean reloading) {
        Objects.requireNonNull(yaml, "yaml");
        Objects.requireNonNull(node, "node");

        if (node instanceof SectionHeaderNode) {
            return true;
        }

        final String path = node.getYmlPath();
        try {
            Object parsed = validatedValue(node, readNode(yaml, node));
            if (reloading && node.isRestartRequired()) {
                if (!Objects.equals(node.getValue(), parsed) && log != null) {
                    log.info("Config key '" + path + "' requires a restart to apply.");
                }
                return true;
            }
            ((ReloadableConfigNode<Object>) node).setValue(parsed);
            return true;

        } catch (RuntimeException ex) {
            boolean retained = reloading && node.isRestartRequired();
            if (!retained) ((ReloadableConfigNode<Object>) node).setValue(node.getDefaultValue());
            if (log != null) {
                log.severe("Failed to load '" + path + "' as "
                        + node.getDataType().getSimpleName()
                        + (node instanceof ReloadableListNode<?> ? " list" : "")
                        + (retained ? " — retaining active value" : " — using default: " + String.valueOf(node.getDefaultValue()))
                        + " \nCause: " + ex.getMessage());
            }
            return false;
        }
    }

    @SuppressWarnings("unchecked")
    private static Object readNode(FileConfiguration yaml, ReloadableConfigNode<?> node) {
        if (node instanceof ReloadableListNode<?> listNode) {
            return YMLLoader.getList(yaml, node.getYmlPath(), listNode.getElementType());
        }
        return YMLLoader.get(yaml, node.getYmlPath(), (Class<Object>) node.getDataType());
    }

    @SuppressWarnings("unchecked")
    private static Object validatedValue(ReloadableConfigNode<?> node, Object value) {
        Object candidate = value instanceof List<?> list ? List.copyOf(list) : value;
        ((ReloadableConfigNode<Object>) node).validateValue(candidate);
        return candidate;
    }

    @SuppressWarnings("unchecked")
    private static void applyValidated(ReloadableConfigNode<?> node, Object value) {
        ((ReloadableConfigNode<Object>) node).applyValidatedValue(value);
    }

    public Class<E> enumType() { return enumType; }

    public @NotNull @UnmodifiableView List<E> keys() { return Collections.unmodifiableList(List.of(keys)); }

    public ReloadableConfigNode<?> node(E key) { return map.get(key); }

    public Object get(@NotNull E key) { return key.node().getValue(); }

    public <T> T get(@NotNull E key, Class<T> requested) { return key.getValue(requested); }

    @SuppressWarnings("unchecked")
    public synchronized <T> void set(@NotNull E key, T value) {
        Object validated = validatedValue(key.node(), value);
        ((ReloadableConfigNode<Object>) key.node()).setValue(validated);
        this.yaml.set(key.getPath(), key.node().getValue());
    }

    public synchronized void save() throws IOException {
        YMLBuilder.savePretty(this.yaml, this.configFile, map.values());
    }

    public FileConfiguration yaml() { return this.yaml; }
    public Plugin getPlugin()       { return plugin; }

    public File getConfigFile() { return configFile; }

    public @NotNull @UnmodifiableView Collection<ReloadableConfigNode<?>> nodes() {
        return Collections.unmodifiableCollection(map.values());
    }
}
