package com.earthpol.earthpollib.config;

import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.plugin.Plugin;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.UnmodifiableView;

import java.io.File;
import java.io.IOException;
import java.util.Collection;
import java.util.Collections;
import java.util.EnumMap;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.logging.Logger;

/**
 * Binds a YAML configuration file to a specific enum of keys
 * ({@code E extends Enum & ReloadableConfiguration}).
 *
 * <p>Responsibilities:</p>
 * <ul>
 *   <li>Stores the enum class and constants in declaration order.</li>
 *   <li>Maintains an {@link EnumMap} from enum constant to its {@link ReloadableConfigNode}.</li>
 *   <li>Creates the config file if missing, writes/fills defaults from the enum’s nodes, and
 *       reparses values from disk into the nodes.</li>
 * </ul>
 *
 * <p><strong>Sync model:</strong> Node values are refreshed from disk on construction and on
 * {@link #reload()}. If you change values through {@link #set(Enum, Object)}, both the in-memory
 * node value and the in-memory YAML are updated; call {@link #save()} to persist those changes.
 * If you mutate the raw {@link #yaml()} directly, call {@link #save()} followed by {@link #reload()}
 * to reparse values back into nodes.</p>
 *
 * @param <E> the enum type that implements {@link ReloadableConfiguration}
 * @since 1.5.0
 */
@SuppressWarnings("unused")
public final class ReloadableConfigHandler<E extends Enum<E> & ReloadableConfiguration> {

    private final Plugin plugin;
    private final File configFile;
    private final Class<E> enumType;
    private final E[] keys;
    private final EnumMap<E, ReloadableConfigNode<?>> map;
    private YamlConfiguration yaml;

    private static final List<String> configHeader =
            List.of(
                    "Config file generated by EarthPolLib",
                    "This file is initially generated from code defaults.",
                    "If a key is missing or malformed, the plugin will fall back to the default value.",
                    "Strings can be quoted or unquoted. If a string doesn't parse correctly, try quoting it."
            );

    public ReloadableConfigHandler(Plugin plugin,
                                   String configFileName,
                                   Class<E> enumType) throws IOException {

        this.plugin   = Objects.requireNonNull(plugin, "plugin");
        this.enumType = Objects.requireNonNull(enumType, "enumType");

        this.keys = enumType.getEnumConstants();
        if (this.keys == null) throw new IllegalArgumentException("Not an enum: " + enumType);

        this.map = new EnumMap<>(enumType);
        final Set<String> seenPaths = new HashSet<>();
        for (E k : keys) {
            ReloadableConfigNode<?> node = k.node();
            String path = node.getYmlPath();
            if (!seenPaths.add(path)) {
                throw new IllegalStateException("Duplicate config node path detected: " + path
                        + " (in " + enumType.getSimpleName() + ")");
            }
            map.put(k, node);
        }

        boolean isNew = !(new File(plugin.getDataFolder(), configFileName)).exists();
        this.configFile = YMLBuilder.fileInitialSetup(plugin, configFileName);

        Collection<ReloadableConfigNode<?>> nodesView = map.values();
        if (isNew) {
            YMLBuilder.buildNewConfiguration(this.configFile, nodesView, configHeader);
        } else {
            YMLBuilder.fillMissingDefaults(this.configFile, nodesView, configHeader);
        }

        this.yaml = YamlConfiguration.loadConfiguration(this.configFile);
        this.yaml.options().parseComments(true);
        reparseIntoNodes();
    }

    public boolean reload() throws IOException {
        YMLBuilder.fillMissingDefaults(
                this.configFile,
                map.values(),
                configHeader
        );
        this.yaml = YamlConfiguration.loadConfiguration(this.configFile);
        this.yaml.options().parseComments(true);
        return reparseIntoNodes();
    }

    @SuppressWarnings("unchecked")
    private boolean reparseIntoNodes() {
        boolean ok = true;
        Logger log = plugin.getLogger();
        for (ReloadableConfigNode<?> n : map.values()) {
            ok &= loadIntoNode(this.yaml, n, log);
        }
        return ok;
    }

    @SuppressWarnings("unchecked")
    private static boolean loadIntoNode(FileConfiguration yaml,
                                        ReloadableConfigNode<?> node,
                                        Logger log) {
        Objects.requireNonNull(yaml, "yaml");
        Objects.requireNonNull(node, "node");

        if (node instanceof SectionHeaderNode) {
            return true;
        }

        final String path = node.getYmlPath();
        try {
            if (node instanceof ReloadableListNode<?> listNode) {
                Class<?> elem = Objects.requireNonNull(listNode.getElementType(), "list elementType");
                List<?> parsed = YMLLoader.getList(yaml, path, (Class<Object>) elem);
                ((ReloadableConfigNode<List<?>>) (ReloadableConfigNode<?>) listNode).setValue(parsed);
            } else {
                Class<Object> type = (Class<Object>) node.getDataType();
                Object parsed = YMLLoader.get(yaml, path, type);
                ((ReloadableConfigNode<Object>) node).setValue(parsed);
            }
            return true;

        } catch (RuntimeException ex) {
            ((ReloadableConfigNode<Object>) node).setValue(node.getDefaultValue());
            if (log != null) {
                log.severe("Failed to load '" + path + "' as "
                        + node.getDataType().getSimpleName()
                        + (node instanceof ReloadableListNode<?> ? " list" : "")
                        + " — using default: " + String.valueOf(node.getDefaultValue())
                        + " \nCause: " + ex.getMessage());
            }
            return false;
        }
    }

    public Class<E> enumType() { return enumType; }

    public @NotNull @UnmodifiableView List<E> keys() { return Collections.unmodifiableList(List.of(keys)); }

    public ReloadableConfigNode<?> node(E key) { return map.get(key); }

    public Object get(@NotNull E key) { return key.node().getValue(); }

    public <T> T get(@NotNull E key, Class<T> requested) { return key.getValue(requested); }

    @SuppressWarnings("unchecked")
    public <T> void set(@NotNull E key, T value) {
        this.yaml.set(key.getPath(), value);
        ((ReloadableConfigNode<Object>) key.node()).setValue(value);
    }

    public void save() throws IOException {
        YMLBuilder.savePretty(this.yaml, this.configFile, map.values());
    }

    public FileConfiguration yaml() { return this.yaml; }
    public Plugin getPlugin()       { return plugin; }

    public File getConfigFile() { return configFile; }

    public @NotNull @UnmodifiableView Collection<ReloadableConfigNode<?>> nodes() {
        return Collections.unmodifiableCollection(map.values());
    }
}
